---
- import_playbook: launch.yaml
- name: Creating Hadoop environment
  hosts: aws_region_ap_south_1
  gather_facts: false
  remote_user: ec2-user
  vars:
    - ansible_ssh_private_key_file: /root/ARTH_DN.pem
  tasks:


    - name: Downloading Hadoop and JDK
      copy:
        src: "{{ item }}"
        dest: /root/
      loop:
        - /root/hadoop-1.2.1-1.x86_64.rpm
        - /root/jdk-8u171-linux-x64.rpm
      notify: Install Hadoop


    - name: Installing JDK
      yum:
        name: /root/jdk-8u171-linux-x64.rpm
        state: present
        disable_gpg_check: yes


    - name: Freeing RAM
      command:
        cmd: echo 3 > /proc/sys/vm/drop_caches
        warn: no


  handlers:
    - name: Installing Hadoop
      command:
        cmd: rpm -i /root/hadoop-1.2.1-1.x86_64.rpm --force 
        warn: no


- import_playbook: master.yaml

- import_playbook: slave.yaml
