---
- name: Writing configuration files for Hadoop Master
  hosts: tag_Name_Arth_MN
  gather_facts: false
  remote_user: ec2-user
  vars:
    - node_name: name
    - ip: 0.0.0.0
    - ansible_ssh_private_key_file: /root/ARTH_DN.pem
  tasks:


    - name: Creating directory for Hadoop MasterNode storage
      file:
        state: directory
        path: /nn
      notify: Formatting Hadoop Master storage


    - name: Writing hdfs-site
      template:
        src: /root/arth_ws/ansible_ws/hadoop/hadoop_ws/hdfs-site.xml
        dest: /etc/hadoop/hdfs-site.xml
    

    - name: Writing core-site
      template:
        src: /root/arth_ws/ansible_ws/hadoop/hadoop_ws/core-site-nn.xml.j2
        dest: /etc/hadoop/core-site.xml


    - name: Starting Hadoop Master service
      command:
        cmd: hadoop-daemon.sh start namenode
        warn: no


    handlers:
    - name: Formatting Hadoop Master storage
      command:
        cmd: hadoop namenode -format
        warn: no
