---
- name: Writing configuration files for Hadoop Slave
  hosts: tag_Name_Arth_DN
  gather_facts: false
  remote_user: ec2-user
  vars:
    - node_name: data
    - ansible_ssh_private_key_file: /root/ARTH_DN.pem
    - dir: /dn
  tasks:

    - name: Creating directory for Hadoop DataNode storage
      file:
        state: directory
        path: "{{ dir }}"


    - name: Retrieving variables from variable file
      include_vars:
        file: varFile.yaml


    - name: Writing hdfs-site
      template:
        src: /root/arth_ws/ansible_ws/hadoop/hadoop_ws/hdfs-site.xml
        dest: /etc/hadoop/hdfs-site.xml


    - name: Writing core-site
      template:
        src: /root/arth_ws/ansible_ws/hadoop/hadoop_ws/core-site-dn.xml.j2
        dest: /etc/hadoop/core-site.xml


    - name: Starting Hadoop Slave service
      command:
        cmd: "hadoop-daemon.sh start datanode"
        warn: no
